<?php

$FunctionList = array();
$FunctionList['node_list'] = array( 'name' => 'node_list',
                                  'operation_types' => array( 'read' ),
                                  'call_method' => array( 'class' => 'eZTagsFunctionCollection',
                                                          'method' => 'fetchNodeList' ),
                                  'parameter_type' => 'standard',
                                  'parameters' => array( array( 'name' => 'alphabet',
                                                                'type' => 'string',
                                                                'required' => true ),
                                                         array( 'name' => 'classid',
                                                                'type' => 'mixed',
                                                                'required' => false,
                                                                'default' => false ),
                                                         array( 'name' => 'offset',
                                                                'type' => 'integer',
                                                                'required' => false,
                                                                'default' => false ),
                                                         array( 'name' => 'limit',
                                                                'type' => 'integer',
                                                                'required' => false,
                                                                'default' => false ),
                                                         array( 'name' => 'owner',
                                                                'type' => 'integer',
                                                                'required' => false,
                                                                'default' => false ),
                                                         array( 'name' => 'sort_by',
                                                                'type' => 'array',
                                                                'required' => false,
                                                                'default' => array() ),
                                                         array( 'name' => 'parent_node_id',
                                                                'type' => 'integer',
                                                                'required' => false,
                                                                'default' => false ) ) );


$FunctionList['node_list_count'] = array( 'name' => 'node_list_count',
                                        'operation_types' => array( 'read' ),
                                        'call_method' => array( 'class' => 'eZTagsFunctionCollection',
                                                                'method' => 'fetchNodeListCount' ),
                                        'parameter_type' => 'standard',
                                        'parameters' => array( array( 'name' => 'alphabet',
                                                                      'type' => 'string',
                                                                      'required' => true ),
                                                               array( 'name' => 'classid',
                                                                      'type' => 'mixed',
                                                                      'required' => false,
                                                                      'default' => false ),
                                                               array( 'name' => 'owner',
                                                                      'type' => 'integer',
                                                                      'required' => false,
                                                                      'default' => false ),
                                                               array( 'name' => 'parent_node_id',
                                                                      'type' => 'integer',
                                                                      'required' => false,
                                                                      'default' => false ) ) );

$FunctionList['object'] = array( 'name' => 'object',
                                        'operation_types' => array( 'read' ),
                                        'call_method' => array( 'class' => 'eZTagsFunctionCollection',
                                                                'method' => 'fetchTagObject' ),
                                        'parameter_type' => 'standard',
                                        'parameters' => array( array( 'name' => 'keyword',
                                                                      'type' => 'string',
                                                                      'required' => true ) ) );
?>
